-- MySQL Script generated by MySQL Workbench
-- Wed Nov  6 16:49:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GALAXY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GALAXY` (
  `Name` VARCHAR(30) NOT NULL,
  `Age` FLOAT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STAR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STAR` (
  `Name` VARCHAR(20) NOT NULL,
  `Position_Latitude` FLOAT NULL,
  `Position_Longitude` FLOAT NULL,
  `Spectral_Type` VARCHAR(10) NULL,
  `Magnitude` FLOAT NULL,
  `Velocity_Heliocentric` FLOAT NULL,
  `Velocity_Rotational` FLOAT NULL,
  `Galaxy_Name` VARCHAR(30) NULL,
  PRIMARY KEY (`Name`),
  INDEX `Galaxy_Name_idx` (`Galaxy_Name` ASC) VISIBLE,
  CONSTRAINT `Galaxy_Name`
    FOREIGN KEY (`Galaxy_Name`)
    REFERENCES `mydb`.`GALAXY` (`Name`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
